[tools]
"go:github.com/google/addlicense" = "latest"
clang-format = "latest"
cmake = "latest"
fd = "latest"
just = "latest"
ninja = "latest"
python = "prefix:3.12"
uv = "latest"

[settings]
experimental = true
