name: Benchmark Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  benchmark:
    name: Run Benchmarks
    # Only run if the CI workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  # Only run on Linux to simplify

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for benchmarking against previous commit

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
          install: true

      - name: Setup Environment
        run: |
          mise x -- just setup
          
          # Install hyperfine in mise
          mise use hyperfine@latest
      
      - name: Create benchmarks directory
        run: mkdir -p benchmarks

      # Build and run tests for the current commit
      - name: Build for current commit
        run: mise x -- just build

      - name: Get parent commit
        id: get-parent
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "parent_sha=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})" >> $GITHUB_OUTPUT
          else
            echo "parent_sha=$(git rev-parse HEAD~1)" >> $GITHUB_OUTPUT
          fi

      - name: Checkout parent commit
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-parent.outputs.parent_sha }}
          clean: false
          path: parent_commit

      - name: Build parent commit
        run: |
          cd parent_commit
          mise trust
          mise install
          mise x -- just build

      - name: Run benchmarks with hyperfine
        run: |
          mise x -- hyperfine --warmup 3 \
            --export-markdown benchmarks/benchmark-results.md \
            --command-name "Current commit" "./build/examples/benchmark" \
            --command-name "Parent commit" "./parent_commit/build/examples/benchmark"

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/benchmark-results.md
