name: Build Workflow

on:
  workflow_call:
    inputs:
      run_full_ci:
        description: 'Whether to run the full CI suite'
        required: false
        default: false
        type: boolean

jobs:
  build-linux:
    name: Build CPace on Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MISE_PAT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for benchmarking against previous commit

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
          install: true

      - name: Setup Environment
        run: |
          mise trust
          mise install
          mise x -- uv venv
          mise x -- uv sync
          
          # Install tools on Linux
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Run CI
        if: inputs.run_full_ci
        run: mise x -- just ci

      - name: Build and Test Only
        if: "!inputs.run_full_ci"
        run: |
          mise x -- just build
          mise x -- just test

  build-macos:
    name: Build CPace on macOS
    needs: build-linux
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MISE_PAT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for benchmarking against previous commit

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
          install: true

      - name: Setup Environment
        run: |
          mise trust
          mise install
          mise x -- uv venv
          mise x -- uv sync

      - name: Run CI
        if: inputs.run_full_ci
        run: mise x -- just ci

      - name: Build and Test Only
        if: "!inputs.run_full_ci"
        run: |
          mise x -- just build
          mise x -- just test
