name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build.yml
    with:
      run_full_ci: true