name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test: # Renamed job for clarity
    name: Build & Test (Matrix)
    uses: ./.github/workflows/build.yml
    with:
      run_full_ci: true
      build_fuzzers: true # <<< ADD THIS LINE
    # Add secrets if needed by build.yml (e.g., MISE_PAT)
    secrets: inherit
