name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  shared-build:
    name: Shared Build & Test
    uses: ./.github/workflows/build.yml
    with:
      run_full_ci: true
    
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [shared-build]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: cpace:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run CI checks in Docker
        run: |
          docker run --rm cpace:latest bash -c "cd /app && just ci"